In [103]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [104]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [105]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [106]:
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [107]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.975
Model:                            OLS   Adj. R-squared:                  0.973
Method:                 Least Squares   F-statistic:                     602.3
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           4.13e-72
Time:                        20:39:29   Log-Likelihood:                -362.20
No. Observations:                 100   AIC:                             738.4
Df Residuals:                      93   BIC:                             756.6
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -29.5262      6.128     -4.818      0.000     -41.695     -17.357
X1             1.1431      0.110     10.353      0.000       0.924       1.362
X2             1.5640      0.048     32.393      0.000       1.468       1.660
X3             1.0936      0.089     12.345      0.000       0.918       1.270
X4             0.6876      0.101      6.836      0.000       0.488       0.887
X5            -2.1218      0.046    -45.768      0.000      -2.214      -2.030
X6            -0.8224      0.081    -10.210      0.000      -0.982      -0.662
==============================================================================
Omnibus:                        0.768   Durbin-Watson:                   2.050
Prob(Omnibus):                  0.681   Jarque-Bera (JB):                0.343
Skew:                           0.071   Prob(JB):                        0.842
Kurtosis:                       3.249   Cond. No.                         464.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [108]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [109]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [110]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.975
Model:                            OLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     288.4
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           1.42e-64
Time:                        20:39:29   Log-Likelihood:                -361.06
No. Observations:                 100   AIC:                             748.1
Df Residuals:                      87   BIC:                             782.0
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -21.7689      9.074     -2.399      0.019     -39.804      -3.734
X1             1.1270      0.117      9.649      0.000       0.895       1.359
X2             1.5652      0.053     29.653      0.000       1.460       1.670
X3             1.0906      0.092     11.896      0.000       0.908       1.273
X4             0.6811      0.104      6.547      0.000       0.474       0.888
X5            -2.1149      0.049    -43.167      0.000      -2.212      -2.018
X6            -0.8201      0.084     -9.770      0.000      -0.987      -0.653
X7            -0.0142      0.117     -0.122      0.903      -0.246       0.218
X8             0.0154      0.047      0.330      0.742      -0.077       0.108
X9            -0.0761      0.086     -0.885      0.379      -0.247       0.095
X10           -0.0982      0.122     -0.803      0.424      -0.341       0.145
X11            0.0263      0.050      0.524      0.601      -0.073       0.126
X12           -0.0134      0.090     -0.150      0.881      -0.191       0.165
==============================================================================
Omnibus:                        0.807   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.668   Jarque-Bera (JB):                0.356
Skew:                          -0.002   Prob(JB):                        0.837
Kurtosis:                       3.292   Cond. No.                         947.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [111]:
y=-30+0.4*x_1+0.6*x_2+3.1*x_3+0.7*x_8-2.1*x_5-0.9*x_9+epsilon

In [112]:
X_ext = X_ext.drop(columns=['Constant'])

In [124]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account


model_lasso = lm.Lasso(alpha=100).fit(X_ext,y)
model_lasso.coef_

array([ 0.        ,  0.13479556,  2.1547165 ,  0.        , -1.94643964,
        0.        , -0.        ,  0.44167744, -0.13854316, -0.        ,
        0.        , -0.        ])

In [114]:
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 7.68110540e-02,  5.31582574e-01,  2.98574784e+00, -0.00000000e+00,
       -2.09102013e+00,  1.54030960e-02, -0.00000000e+00,  7.00325487e-01,
       -9.11832782e-01, -0.00000000e+00,  1.71469575e-03,  0.00000000e+00])

In [115]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 0.22603378,  0.56480723,  3.08781382, -0.01862842, -2.11453683,
        0.08004394, -0.01432826,  0.71514498, -0.9754489 , -0.09824119,
        0.02638572, -0.01337677])

In [121]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([-0.05010018,  0.32983771,  1.65771352,  0.04071867, -1.75895731,
        0.10011233, -0.08052616,  0.53731596, -0.56943529, -0.08552489,
        0.0703879 , -0.00893031])

In [117]:
model_redige = lm.Ridge(alpha=10).fit(X_ext, y)
model_ridge.coef_

array([-0.05010018,  0.32983771,  1.65771352,  0.04071867, -1.75895731,
        0.10011233, -0.08052616,  0.53731596, -0.56943529, -0.08552489,
        0.0703879 , -0.00893031])

In [118]:
model_ridge = lm.Ridge(alpha=1000).fit(X_ext, y)
model_ridge.coef_

array([ 0.1469961 ,  0.52613449,  2.83582999,  0.00475252, -2.07544279,
        0.09481243, -0.02584396,  0.69157324, -0.91238875, -0.09793964,
        0.03713932, -0.01100809])